import { RHFInput } from "@/components/RHFInput";
import { FormProvider } from "react-hook-form";
import { usePromptForm } from "../hooks/usePromptForm";
import type { PromptFormValues } from "../schemas";
import type { PromptCreate } from "@/services";
import { useNavigate } from "react-router";
import { MODELS } from "@/constants";
import { Button } from "@/components/ui/button";
import { RHFTextArea } from "@/components/RHFTextarea";
import { RHFSelect } from "@/components/RHFSelect";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Image, Type } from "lucide-react";

type PromptFormProps = {
  mode: "create" | "edit";
  onSubmit: (data: PromptFormValues) => void;
  isLoading?: boolean;
  defaultValues?: PromptCreate;
  onDelete?: () => void;
};

export function PromptForm({
  mode,
  onSubmit,
  isLoading,
  defaultValues,
  onDelete,
}: PromptFormProps) {
  const navigate = useNavigate();
  const methods = usePromptForm({ defaultValues });
  const handleSubmit = methods.handleSubmit((data) => {
    onSubmit(data);
    if (mode === "create") {
      methods.reset();
    }
  });

  const handleOnDelete = () => {
    if (onDelete) {
      onDelete();
    }
  };

  const handleOnCancel = () => {
    navigate("/");
  };

  return (
    <FormProvider {...methods}>
      <form className="flex flex-col gap-6" onSubmit={handleSubmit}>
        <RHFInput
          name="title"
          label="Title"
          placeholder="Put a title that summarizes your prompt"
        />
        <RHFTextArea
          name="description"
          label="Description"
          placeholder="Describe the purpose of your prompt. What problem does it solve? What do you achieve with it?"
        />
        <RHFTextArea
          name="prompt"
          label="Prompt"
          placeholder="Your prompt here"
        />
        <RHFSelect
          name="model"
          label="Model"
          options={MODELS}
          placeholder="Select a model"
        />
        <div className="space-y-2">
          <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            Result Preview
          </label>

          <Tabs defaultValue="text" className="w-full">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger
                value="text"
                className="gap-2"
                data-testid="text-result-tab"
              >
                <Type className="size-4" /> Text Result
              </TabsTrigger>
              <TabsTrigger
                value="media"
                className="gap-2"
                data-testid="media-result-tab"
              >
                <Image className="size-4" /> Media URL
              </TabsTrigger>
            </TabsList>

            <TabsContent
              value="text"
              className="mt-4 animate-in fade-in slide-in-from-top-2"
            >
              <RHFTextArea
                name="resultExample"
                label="Text Output"
                placeholder="Paste the text result generated by the LLM..."
              />
            </TabsContent>

            <TabsContent
              value="media"
              className="mt-4 animate-in fade-in slide-in-from-top-2"
            >
              <RHFInput
                name="mediaUrl"
                label="Image/Video URL"
                placeholder="https://example.com/image.png or YouTube Link"
              />
              <p className="text-sm text-muted-foreground mt-2">
                Support images, links to resources and YouTube videos.
              </p>
            </TabsContent>
          </Tabs>
        </div>

        <div className="flex justify-between sm:justify-end sm:gap-4">
          <Button type="button" variant="outline" onClick={handleOnCancel}>
            Cancel
          </Button>
          {mode === "edit" ? (
            <Button
              variant="destructive"
              onClick={handleOnDelete}
              type="button"
              disabled={isLoading}
            >
              Delete
            </Button>
          ) : null}
          <Button type="submit" disabled={isLoading}>
            {mode === "create" ? "Share" : "Save changes"}
          </Button>
        </div>
      </form>
    </FormProvider>
  );
}
