export const MODELS = [
  { id: "gemini-3-pro", label: "Gemini 3 Pro" },
  { id: "gemini-3-flash", label: "Gemini 3 Flash" },
  { id: "gemini-3-thinking", label: "Gemini 3 Thinking" },
  { id: "nanobanana", label: "Nanobanana" },
  { id: "grok-auto", label: "Grok Auto" },
  { id: "grok-fast", label: "Grok Fast" },
  { id: "grok-expert", label: "Grok Expert" },
  { id: "grok-4.1-thinking", label: "Grok 4.1 thinking" },
  { id: "chatgpt-free", label: "ChatGPT Free" },
  { id: "gpt-5.2", label: "GPT 5.2" },
  { id: "gpt-5.2-codex", label: "GPT 5.2 Codex" },
  { id: "gpt-5.1", label: "GPT 5.1" },
  { id: "gpt-5.1-medium", label: "GPT 5.1 Medum" },
  { id: "gpt-5.1-codex", label: "GPT 5.1 Codex" },
  { id: "claude-sonnet-4.5", label: "Claude Sonnet 4.5" },
  { id: "claude-haiku-4.5", label: "Claude Hiku 4.5" },
  { id: "claude-opus-4.5", label: "Claude Opus 4.5" },
  { id: "claude-sonnet-4", label: "Claude Sonnet 4" },
  { id: "claude-haiku-3.5", label: "Claude Hiku 3.5" },
  { id: "claude-opus-4", label: "Claude Opus 4" },
  { id: "qwen3-max", label: "Qwen3 Max" },
  { id: "qwen3-vl-235b-a22b", label: "Qwen3-VL-235B-A22B"},
  { id: "qwen3-coder", label: "Qwen3 Coder" },
  { id: "qwen3-vl-32b", label: "Qwen3 VL 32B" },
  { id: "microsoft-365-copilot", label: "Microsoft 365 Copilot" },
  { id: "stablediffusion-free", label: "Stablediffusion Free" },
  { id: "stablediffusion-pro", label: "Stablediffusion Pro" },
  { id: "midjourney", label: "Midjourney" },
  { id: "kimi-k2.5-instant", label: "Kimmi k2.5 Instant" },
  { id: "kimi-k2.5-thinking", label: "Kimmi k2.5 Thinking" },
  { id: "kimi-k2.5-agent", label: "Kimmi k2.5 Agent" },
  { id: "kimi-k2.5-agent-swarm", label: "Kimmi k2.5 Agent Swarm" },
  { id: "deepseek", label: "DeepSeek" },
  { id: "mistra-lechat", label: "Mistral Le Chat" },
  { id: "veo-3", label: "Veo 3" },
  { id: "sora-2", label: "Sora 2" },
];
